import React from "react";
import Head from "next/head";
import HeaderSlider from "../components/slider/index";
import FilmSlider from "../components/film-slider";
import {Divider} from "antd";
import FilmsPoster from "../components/film-poster";
import axios from "axios";

export default function Home({data}) {

    console.log(data, "is data")

    return (
        <div>
            <Head>
                <title>صفحه اصلی || تاپ فیلم</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <HeaderSlider/>
                <Divider orientation="right">
                    <h2>
                        برترين فيلم ها
                    </h2>
                </Divider>
                <FilmSlider key="popular" data={data.popular}/>
                <Divider orientation="right">
                    <h2>
                        آخرین فيلم ها
                    </h2>
                </Divider>
                <FilmSlider dark key="recent" data={data.recent}/>
                <FilmsPoster/>
                <Divider orientation="right">
                    <h2>
                        قدیمی ترین فيلم ها
                    </h2>
                </Divider>
                <FilmSlider dark key="old" data={data.old}/>
            </div>
        </div>
    );
}

export async function getServerSideProps(context) {
    const data = (await axios.get("/api/films")).data

    return {
        props: {
            data
        }
    }
}
